### PR TITLE
Revert "sepolicy: ignore neverallows"

### PR DESCRIPTION
**Pull request by anayw2001**
This reverts commit 8d53b9a84dc7558f4f428e2cf597bfbeadd4326f.

### CODE REVIEW

**Comment by Martinusbe** [comment]
this will break many devices though if sepolicy isn't good

**Comment by GtrCraft** [comment]
> this will break many devices though if sepolicy isn't good

isn't that up to the maintainer?

**Comment by anayw2001** [comment]
mata sepolicy is good

**Comment by Martinusbe** [comment]
> > this will break many devices though if sepolicy isn't good
> 
> isn't that up to the maintainer?

sure

**Pull request closed without merging**
