### PR TITLE
add lenovo zuk z1 (ham)

### PR DESCRIPTION
**Pull request by Ram9199**

### CODE REVIEW

**Comment by CheckYourScreen** [comment]
Finally a commit which will increase performance by 80% and sot by 2hrs..

**Comment by Ram9199** [comment]
what ??

**Comment by ghost** [comment]
Good work. Can you add my device too (memedo)? I want official

**Comment by alamo18** [comment]
Good work. Can you add my device too (memedo)? I want official

**Comment by CheckYourScreen** [comment]
Go through gzosp gerrit.
I'll -1 both of you 🤣
I wish it had -∞..

**Comment by CheckYourScreen** [comment]
Jokes aside, z1 seems good to go official from my side +1.
Need other members approval so..

**Comment by Ram9199** [comment]
ok i can wait for it bruh and tq

**Pull request closed without merging**
